ALTER TABLE provider_accounts ADD COLUMN IF NOT EXISTS weight INTEGER NOT NULL DEFAULT 100;
ALTER TABLE provider_accounts ADD COLUMN IF NOT EXISTS rpm_limit INTEGER NOT NULL DEFAULT 0;
ALTER TABLE provider_accounts ADD COLUMN IF NOT EXISTS tpm_limit INTEGER NOT NULL DEFAULT 0;
ALTER TABLE provider_accounts ADD COLUMN IF NOT EXISTS circuit_state TEXT NOT NULL DEFAULT 'closed';
ALTER TABLE provider_accounts ADD COLUMN IF NOT EXISTS circuit_failure_threshold INTEGER NOT NULL DEFAULT 5;
ALTER TABLE provider_accounts ADD COLUMN IF NOT EXISTS circuit_open_seconds INTEGER NOT NULL DEFAULT 60;
ALTER TABLE provider_accounts ADD COLUMN IF NOT EXISTS consecutive_failures INTEGER NOT NULL DEFAULT 0;
ALTER TABLE provider_accounts ADD COLUMN IF NOT EXISTS circuit_opened_until TIMESTAMPTZ;
ALTER TABLE provider_accounts ADD COLUMN IF NOT EXISTS last_failure_at TIMESTAMPTZ;
