ALTER TABLE gateway_models ADD COLUMN IF NOT EXISTS sticky_enabled BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE gateway_models ADD COLUMN IF NOT EXISTS sticky_ttl_seconds INTEGER NOT NULL DEFAULT 1800;
