ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS artifact_sink_id TEXT NOT NULL DEFAULT '';
ALTER TABLE ai_operations ADD COLUMN IF NOT EXISTS artifact_sink_id TEXT NOT NULL DEFAULT '';
ALTER TABLE ai_jobs ADD COLUMN IF NOT EXISTS artifact_sink_id TEXT NOT NULL DEFAULT '';
